python ../src/run_bert_crf.py \
    --model_name hfl/chinese-roberta-wwm-ext \
    --learning_rate 3e-5 \
    --num_train_epochs 10 \
    --batch_size 32 \
    --weight_decay 0.01 \
    --train_file ../data/bio_11-20230531/train.json \
    --test_file ../data/bio_11-20230531/test.json \
    --features_file ../data/bio_11-20230531/features.json \
    --output_dir ../tmp/roberta_crf_bio11 \
    --do_train True \
    --do_predict True