python ../src/run_bilstm.py \
    --learning_rate 0.05 \
    --weight_decay 1e-4 \
    --num_train_epochs 300 \
    --batch_size 32 \
    --embedding_dim 50 \
    --hidden_dim 64 \
    --train_file ../data/20230601-bio_13_split/train.json \
    --test_file ../data/20230601-bio_13_split/test.json \
    --features_file ../data/20230601-bio_13_split/features.json \
    --output_dir ../tmp/bilstm \
    --do_train True \
    --do_predict True